### ISSUE TITLE
Make signing methods clearer

### ISSUE THREAD

**Issue by Firaenix** [Firaenix/bsv-wasm#20]
There are different ways to sign a message or message digest dependent on:
- Endianness of the digest when generating ephemeral K
- SHA2 hashing algorithm chosen for signing (SHA256, SHA256d, etc)

Maybe a good way to approach this is having simple sign methods on different structs (like Transaction)
- Transaction Signing
    - Used for signing Sighash buffers
    - Reversed K: true
    - Double SHA256

- Traditional ECDSA Signatures
   - Used for signing any message to be compatible with ECDSA libraries outside of Bitcoin (SSH, Code signing, etc)
   - Reversed K: false
   - Single SHA256

- Bitcoin Signed Messages (BSM)
   - Used for verifying a message has been signed with a Bitcoin P2PKH Address
   - Requires being able to recover a public key from a signature.
   - Reversed K: optional (?)
   - Double SHA256

**Comment by Firaenix** [comment]
Idea:

1. Transaction.sign() - Sighash signing
2. PrivateKey.signBitcoinMessage() - BSM Signing
3. PrivateKey.sign() / PrivateKey.signTraditional() - Non Bitcoin/Standard ECDSA message signing

**Comment by Firaenix** [comment]
Or if you're signing something to be verified with an Address (BSM), Address.signMessage()

**Comment by hbeckeri** [comment]
![image](https://user-images.githubusercontent.com/8557965/125150387-7d6c3500-e10d-11eb-9cf0-7a5eebe110ba.png)

**Comment by hbeckeri** [comment]
> Or if you're signing something to be verified with an Address (BSM), Address.signMessage()

@Firaenix how would this work? You'd need to still have a private key? Wouldnt it be the same as PrivateKey.signBitcoinMessage()? When you need to verify it you can just get the address from the private key

**Comment by Firaenix** [comment]
Released in 1.1.0
