### ISSUE TITLE
the library is no longer compatible with the stable compiler

### ISSUE THREAD

**Issue by joseluis** [Firaenix/bsv-wasm#38]
I noticed it since I only use the stable compiler and I was surprised by the undocumented breaking change. 

After the following changes the library doesn't compile in stable anymore:
https://github.com/Firaenix/bsv-wasm/blob/67ce940c7c16479257898fa67e414f8a455677a3/Cargo.toml#L15
https://github.com/Firaenix/bsv-wasm/blob/67ce940c7c16479257898fa67e414f8a455677a3/src/lib.rs#L1

I personally don't think removing stable compatibility is a good idea, specially not just to avoid using an ugly long chain of traits in only 3 places...

For now I've removed the feature and the trait alias definition in my local copy in order to be able to keep working with this lib...

**Comment by Firaenix** [comment]
Great point, I actually didn't consider how changing the builds to nightly would impact the usage of the library when other people are using it in Rust. I'll fix that up now.
