### ISSUE TITLE
Memory leak when encrypting/decrypting

### ISSUE THREAD

**Issue by hbeckeri** [Firaenix/bsv-wasm#45]
I have anecdotal evidence that `AES.encrypt` and `AES.decrypt` are causing a memory leak but I don't have any proof, stay sooned

**Comment by Firaenix** [comment]
Maybe related https://github.com/rustwasm/wasm-bindgen/issues/1515

**Comment by Firaenix** [comment]
I have been able to replicate this and I think I've identified the cause in wasm-bindgen

**Comment by Firaenix** [comment]
https://github.com/rustwasm/wasm-bindgen/issues/1963

**Comment by Firaenix** [comment]
Fixed in Release 1.2.2
